#!/usr/bin/env bash

# resolve shell-specifics
case "$(echo "$SHELL" | sed 's|/usr||g')" in
    "/bin/zsh")
        RCPATH="$HOME/.zshrc"
        SOURCE="${BASH_SOURCE[0]:-${(%):-%N}}"
    ;;
    *)
        RCPATH="$HOME/.bashrc"
        if [[ -f "$HOME/.bash_aliases" ]]; then
            RCPATH="$HOME/.bash_aliases"
        fi
        SOURCE="${BASH_SOURCE[0]}"
    ;;
esac

# get base dir regardless of execution location
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE=$([[ "$SOURCE" = /* ]] && echo "$SOURCE" || echo "$PWD/${SOURCE#./}")
basedir=$(dirname "$SOURCE")

. $basedir/scripts/functions.sh

case "$1" in
    "rb" | "rbp" | "rebuild")
    (
        set -e
        cd "$basedir"
        scripts/rebuildpatches.sh "$basedir"
    )
    ;;
    "p" | "patch" | "apply")
    (
        set -e
        cd "$basedir"
	scripts/apply.sh "$basedir"
    )
    ;;
    "up" | "upstream")
    (
	set -e
        cd "$basedir"
	scripts/upstream.sh "$2" "$3"
    )
    ;;
    "push")
    (
        cd "$basedir"
        scripts/push.sh
    )
    ;;
    "nuke" | "reset")
    (
        cd "$basedir"
	rm Paper -Rf
	rm PaperDragon-Server -Rf
	rm PaperDragon-API -Rf
    )
    ;;
    "ci" | "jenkins")
    (
        cd "$basedir"
        rm Paper -Rf
        rm PaperDragon-Server -Rf
        rm PaperDragon-API -Rf
        scripts/upstream.sh
        scripts/apply.sh
    )
    ;;
    "r" | "root")
        cd "$basedir"
    ;;
    "a" | "api")
        cd "$basedir/PaperDragon-API"
    ;;
    "s" | "server")
        cd "$basedir/PaperDragon-Server"
    ;;
    "e" | "edit")
        case "$2" in
            "s" | "server")
            export LAST_EDIT="$basedir/PaperDragon-Server"
            cd "$basedir/PaperDragon-Server"
            (
                set -e

                paperstash
                git rebase -i upstream/upstream
                paperunstash
            )
            ;;
            "a" | "api")
            export LAST_EDIT="$basedir/PaperDragon-API"
            cd "$basedir/PaperDragon-API"
            (
                set -e

                paperstash
                git rebase -i upstream/upstream
                paperunstash
            )
            ;;
            "c" | "continue")
            cd "$LAST_EDIT"
            unset LAST_EDIT
            (
                set -e

                git add .
                git commit --amend
                git rebase --continue

                cd "$basedir"
                scripts/rebuildPatches.sh "$basedir"
            )
            ;;
            *)
                echo "You must edit either the api or server."
            ;;
        esac
    ;;
    "setup")
        if [[ -f "$RCPATH" ]] ; then
            NAME="dragon"
            if [[ ! -z "${2+x}" ]] ; then
                NAME="$2"
            fi
            (grep "alias $NAME=" "$RCPATH" > /dev/null) && (sed -i "s|alias $NAME=.*|alias $NAME='. $SOURCE'|g" "$RCPATH") || (echo "alias $NAME='. $SOURCE'" >> "$RCPATH")
            alias "$NAME=. $SOURCE"
            echo "You can now just type '$NAME' at any time to access the paperdragon tool."
        else
          echo "We were unable to setup the paperdragon build tool alias: $RCPATH is missing"
        fi
    ;;
    *)
        echo "PaperDragon build tool command. This provides a variety of commands to build and manage the PaperDragon build"
        echo "environment. For all of the functionality of this command to be available, you must first run the"
        echo "'setup' command. View below for details. For essential building and patching, you do not need to do the setup."
        echo ""
        echo " Normal commands:"
        echo "  * rb, rebuild       | Rebuild patches, can be called from anywhere."
        echo "  * p, patch, apply   | Apply all patches to the project without building it. Can be run from anywhere."
        echo "  * up, upstream      | Update the Paper Submodule" 
        echo "  * init, submodules  | Initilize the Paper Submodule"
	echo "  * push              | Push the project to the Remote"
	echo "  * nuke, reset       | Reset the Entire Project - WARNING: THIS WILL DELETE EVERYTHING!"
        echo ""
        echo " These commands require the setup command before use:"
        echo "  * r, root           | Change directory to the root of the project."
        echo "  * a. api            | Move to the PaperDragon-API directory."
        echo "  * s, server         | Move to the PaperDragon-Server directory."
        echo "  * e, edit           | Use to edit a specific patch, give it the argument \"server\" or \"api\""
        echo "                      | respectively to edit the correct project. Use the argument \"continue\" after"
        echo "                      | the changes have been made to finish and rebuild patches. Can be called from anywhere."
        echo ""
        echo "  * setup             | Add an alias to $RCPATH to allow full functionality of this script. Run as:"
        echo "                      |     . ./paper setup"
        echo "                      | After you run this command you'll be able to just run 'paper' from anywhere."
        echo "                      | The default name for the resulting alias is 'paper', you can give an argument to override"
        echo "                      | this default, such as:"
        echo "                      |     . ./paper setup example"
        echo "                      | Which will allow you to run 'example' instead."
    ;;
esac

unset RCPATH
unset SOURCE
unset basedir
unset -f color
unset -f colorend
unset -f paperstash
unset -f paperunstash
